
trigger:
- main

pool:
  name: Default #Testing with self-hosted agent

# pool:
#   vmImage: Default

variables:
- group: webapp-dev-group1

resources:
  repositories: 
  - repository: templates
    type: github
    name: rajeshwarandevops/azdevops_pipeline_template
    endpoint: github.com_rajeshwarandevops

steps:
 - template: pipeline_template.yaml@templates
   parameters:
     serviceconnection: $(azureconnection)
     webappname: $(webappname)
 
 
