
trigger:
- main

pool:
  vmImage: Default

variables:
- group: webapp-dev-group

resources:
  repositories: 
  - repository: MyGitHubRepo
    type: github
    name: rajeshwarandevops/azdevops_pipeline_template
    endpoint: github.com/rajeshwarandevops

steps:
 - template: pipeline_template.yaml@templates
   parameters:
     serviceconnection: $(azureconnection)
     webappname: $(webappname)
 
 
